version: "3.8"
services:
  db:
    image: postgres:15
    container_name: dsde-postgres
    environment:
      POSTGRES_USER: dsdeuser
      POSTGRES_PASSWORD: dsdepass
      POSTGRES_DB: dsdedb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dsdeuser"]
      interval: 10s
      timeout: 5s
      retries: 5